projectapp/config/routes.rb
Projectapp::Application.routes.draw do
  resources :profiles

  resources :post_answers

  resources :post_questions do
        collection do
          get 'about'
          get 'feedback'
        end
      end

  devise_for :users
  root 'post_questions#index'

  get 'post_questions/:id/:question' => 'post_questions#show', :as => :show_post_question
  
  

  

end

projectapp/app/models/post_answer.rb
class PostAnswer < ActiveRecord::Base
  validates_presence_of :answer, :post_question_id
  belongs_to :post_question
  belongs_to :user
end

projectapp/app/controllers/post_answers_controller.rb
class PostAnswersController < ApplicationController
  before_action :set_post_answer, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :only => [ :update, :edit, :destroy]

  # GET /post_answers
  # GET /post_answers.json
  def index
    @post_answers = PostAnswer.all
  end

  # GET /post_answers/1
  # GET /post_answers/1.json
  def show
  end

  # GET /post_answers/new
  def new
    @post_answer = PostAnswer.new
  end

  # GET /post_answers/1/edit
  def edit
  end

  # POST /post_answers
  # POST /post_answers.json
  def create
    @post_answer = PostAnswer.new(post_answer_params)
    if current_user.nil?
      @post_answer.user_id = 0
    else
      @post_answer.user_id = current_user.id.to_s
    end
    respond_to do |format|
      if @post_answer.save
        format.html { redirect_to @post_answer.post_question, notice: 'Post answer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post_answer }
      else
        format.html { redirect_to PostQuestion.where(:id => @post_answer.post_question_id).first}
        format.json { render json: @post_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_answers/1
  # PATCH/PUT /post_answers/1.json
  def update
    respond_to do |format|
      if Profile.find_by_user_id(current_user.id).reputation_points > 0 && @post_answer.update(post_answer_params)
        format.html { redirect_to @post_answer.post_question, notice: 'Post answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_answers/1
  # DELETE /post_answers/1.json
  def destroy
    @post_answer.destroy
    respond_to do |format|
      format.html { redirect_to post_answers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_answer
      @post_answer = PostAnswer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_answer_params
      params.require(:post_answer).permit(:answer, :post_question_id, :user_display_name)
    end
end

projectapp/app/helpers/post_answers_helper.rb
module PostAnswersHelper
end

projectapp/app/views/post_answers/_form.html.erb
<%= form_for(@post_answer) do |f| %>
  <% if @post_answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_answer.errors.count, "error") %> prohibited this post_answer from being saved:</h2>

      <ul>
      <% @post_answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_area :answer, :size => "100 x 10" %>
  </div>

  <div class="field">
    <% if current_user.nil?%>
      <%= f.label :user_display_name %><br>
      <%= f.text_field  :user_display_name, :size => "30" %>
    <% else %>
      <%= f.hidden_field :user_display_name, :value => current_user.email %>
    <% end %>
  </div>
  <% if @post_question_id.nil? %>
    <%= f.hidden_field :post_question_id, :value => @post_answer.post_question_id%>
  <% else %>
    <%= f.hidden_field :post_question_id, :value => @post_question_id %>
  <% end %>
  <div class="actions">
    <button class="btn" type="submit" value = "HTML">Post Your Answer</button>
  </div>
<% end %>

projectapp/app/views/post_answers/edit.html.erb
<h1>Editing answer ( Requires 50 reputation points to edit)</h1>

<%= render 'form' %>

projectapp/app/views/post_answers/index.html.erb
<h1>Listing post_answers</h1>

<table>
  <thead>
    <tr>
      <th>Answer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @post_answers.each do |post_answer| %>
      <tr>
        <td><%= post_answer.answer %></td>
        <td><%= link_to 'Show', post_answer %></td>
        <td><%= link_to 'Edit', edit_post_answer_path(post_answer) %></td>
        <td><%= link_to 'Destroy', post_answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post answer', new_post_answer_path %>

projectapp/app/views/post_answers/new.html.erb
<h1>New post_answer</h1>

<%= render 'form' %>

<%= link_to 'Back', post_answers_path %>

projectapp/app/views/post_answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Answer:</strong>
  <%= @post_answer.answer %>
</p>

<%= link_to 'Edit', edit_post_answer_path(@post_answer) %> |
<%= link_to 'Back', post_answers_path %>