projectapp/config/routes.rb
Projectapp::Application.routes.draw do
  resources :profiles

  resources :post_answers

  resources :post_questions do
        collection do
          get 'about'
          get 'feedback'
        end
      end

  devise_for :users
  root 'post_questions#index'

  get 'post_questions/:id/:question' => 'post_questions#show', :as => :show_post_question
  
  

  

end

projectapp/app/models/post_question.rb
class PostQuestion < ActiveRecord::Base
  validates_presence_of :question, :user_id, :body
  validates_length_of :question, minimum:15
  belongs_to :user
  has_many :post_answers
end

projectapp/app/controllers/post_questions_controller.rb
class PostQuestionsController < ApplicationController
  before_action :set_post_question, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :only => [:create, :update, :new, :edit, :destroy]
 

  # GET /post_questions
  # GET /post_questions.json
  def index
    if params[:search]
      search = params[:search]
      @post_questions = PostQuestion.where("question like ? OR body like ?", "%#{search}%", "%#{search}%")

      PostQuestion.all.each do |question|
        if (! @post_questions.find_by_id(question.id))
          answers = question.post_answers.where("answer like ?", "%#{search}%")
          if answers.count > 0
            @post_questions << question
          end
        end
      end
    else 
      @post_questions = PostQuestion.all
    end
    if !current_user.nil? 
      profile = Profile.find_by_user_id(current_user.id)
      profile = Profile.create(:user_id => current_user.id, :reputation_points => 0) if profile.nil?
    end
  end

  # GET /post_questions/1
  # GET /post_questions/1.json
  def show
    @post_question
    @post_answer = PostAnswer.new
    if (params[:answer_id])
      answer = @post_question.post_answers.find_by_id(params[:answer_id])
      answer.number_of_votes+= params[:vote].to_i unless (answer.number_of_votes == 0 && params[:vote].to_i == -1)
      answer.save
      profile = Profile.find_by_user_id(answer.user_id)
      profile.update(:reputation_points => answer.number_of_votes * 50)
    end
    @post_answers = @post_question.post_answers
    @post_question_id = @post_question.id
  end

  # GET /post_questions/new
  def new
    @post_question = PostQuestion.new
  end

  # GET /post_questions/1/edit
  def edit
  end

  # POST /post_questions
  # POST /post_questions.json
  def create
    @post_question = PostQuestion.new(post_question_params)
    @post_question.user_id = current_user.id.to_s
    respond_to do |format|
      if @post_question.save
        format.html { redirect_to show_post_question_path(@post_question, @post_question.question), notice: 'Post question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post_question }
      else
        format.html { render action: 'new' }
        format.json { render json: @post_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_questions/1
  # PATCH/PUT /post_questions/1.json
  def update
    respond_to do |format|
      if @post_question.update(post_question_params)
        format.html { redirect_to show_post_question_path(@post_question, @post_question.question), notice: 'Post question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_questions/1
  # DELETE /post_questions/1.json
  def destroy
    post_answers = @post_question.post_answers
    post_answers.each {|post_answer| post_answer.destroy}
    @post_question.destroy
    respond_to do |format|
      format.html { redirect_to post_questions_url }
      format.json { head :no_content }
    end
  end
  
  def about
  end

  def feedback
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_question
      @post_question = PostQuestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_question_params
      params.require(:post_question).permit(:question, :user_id, :body)
    end
end

projectapp/app/helpers/post_questions_helper.rb
module PostQuestionsHelper
end

projectapp/app/views/post_questions/_answerform.html.erb
<hr width =100% >
<h1 style="color:coral">Answers</h1>
<% @post_answers.each do |post_answer| %>
    <p><%= post_answer.answer %></p>
    <% if !post_answer.user_display_name.nil? && post_answer.user_display_name != ""%>
		<p style="color:coral"><%= "Answered by #{post_answer.user_display_name}"%></p>
	<%else%>
		<p style="color:coral"><%= "Answered by anonymous"%></p>
	<%end%>

    <p><%= "answered #{time_ago_in_words post_answer.created_at} ago" %></p>
     
    <%= post_answer.number_of_votes %> Votes
    <% if !current_user.nil? && current_user.id != post_answer.user_id %>
    | <%= link_to 'Like', {:controller => "post_questions", :action => "show", :vote => 1, :answer_id => post_answer.id } %>|
    
    <% if (post_answer.number_of_votes != 0)%>
    <%= link_to 'Not helpful', {:controller => "post_questions", :action => "show", :vote => -1, :answer_id => post_answer.id } %>
    <% end%>
    |
    <% end%>
    <%= link_to 'Edit', edit_post_answer_path(post_answer) %> (requires 50 reputation points) 
    <% if !current_user.nil? && current_user.id == post_answer.user_id %>
     | <%= link_to 'Destroy', post_answer, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end%>
  <hr width =100% >
<% end %>

projectapp/app/views/post_questions/_form.html.erb
<%= form_for(@post_question) do |f| %>
  <% if @post_question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_question.errors.count, "error") %> prohibited this post_question from being saved:</h2>

      <ul>
      <% @post_question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_field :question, :size => "132" %>
  </div>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, :size => "100x10"%>
  </div>  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

projectapp/app/views/post_questions/about.html.erb
<!DOCTYPE html>
<html>
<head>
        
    <title>About - ErrorsNoMore</title>

    
</head>
<body>        
     <div class="wiki-ph-content">

      <p>Do your programming errors haunt you in your dreams?Yes they did haunt us and why not? We have to get rid of them to get a good night's sleep. This was the inspiration behind this website to service fellow programmers.</p>

        <p ><strong >ErrorsNoMOre</strong> is a question and answer site for professional and enthusiast programmers. <br>Let us share our programming experiences and make errors no more. </p>

    <p><strong style="color:coral">Ask Questions and Get Answers</strong> is the mantra of this website</p>
    <p> Come and enjoy the hassle free way to get solutions to all your programming errors which frequent each one of us in our daily lives. For those who have overcome these errors, share your experiences with others.























    
</div> 
  
                      
</body>
</html>

projectapp/app/views/post_questions/edit.html.erb
<h1>Editing post_question</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_question %> |
<%= link_to 'Back', post_questions_path %>

projectapp/app/views/post_questions/feedback.html.erb
<!DOCTYPE html>
<html>
<head>
        
    <title>About - ErrorsNoMore</title>

    
</head>
<body>        
     <div class="wiki-ph-content">

    

        <p style="color:coral"><strong>Please leave us a feedback at :</strong> </p>
        <p><strong>skambhampati@uh.edu<strong></p>
        <p><strong>dnagarajan@uh.edu<strong></p>
























    
</div> 
  
                      
</body>
</html>

projectapp/app/views/post_questions/index.html.erb
<h1 style="color:coral">Top Questions</h1>
 <% @post_questions.each do |post_question| %>
 <p><strong><%= link_to post_question.question, show_post_question_path(post_question, post_question.question) %></strong></p>
  <p style="color:coral"><%= "By #{post_question.user.email}"%></p>
   <p><%= "asked #{time_ago_in_words post_question.created_at} ago" %></p>
   <%= post_question.post_answers.count %> Answers
   <hr width =100% >
    <% end %>

projectapp/app/views/post_questions/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', post_questions_path %>

projectapp/app/views/post_questions/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<h1>
  <strong><%= @post_question.question %></strong>
  
</h1>

<p>
  <%= @post_question.body %>
</p>

<p>
  <strong>"asked by"</strong>
  <%= @post_question.user.email %>
</p>
<p><%= time_ago_in_words @post_question.created_at  %> ago</p>
<%= @post_question.post_answers.count %> Answers
<% if !current_user.nil? && current_user.id == @post_question.user_id %>
<%= link_to 'Edit', edit_post_question_path(@post_question) %> | 
<%= link_to 'Destroy', @post_question, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end%>
<%= link_to 'Back', post_questions_path %>


<%= render :partial => 'answerform', :locals => {:post_answers => @post_answers }%>
<%= render :partial => '/post_answers/form', :locals => {:post_answer => @post_answer, :post_question_id => params[:id]} %>